name: Run CI checks on pull request
'on':
  pull_request:
    branches:
      - main
      - develop
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        run: yarn install

      - name: Run tests
        run: yarn test
